name: Update Loto JSON

on:
  schedule:
    - cron: '0 9 * * *'  # rulează zilnic la ora 9:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run scraper script
        run: node dorin_buraca_loto-system.js

      - name: Push toate-extragerile.json to gh-pages
        run: |
          mkdir temp-gh
          cp toate-extragerile.json temp-gh/
          cd temp-gh

          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git checkout -b gh-pages
          git add toate-extragerile.json
          git commit -m "🔄 Update toate-extragerile.json"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages:gh-pages
