name: Loto 6/49 Scraper

on:
  schedule:
    - cron: '0 4 * * *' # Rulează zilnic la 04:00 UTC (07:00 România)
  workflow_dispatch: # opțional - permite rulare manuală

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonare repository
        uses: actions/checkout@v3

      - name: Instalare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalare pachete
        run: npm install axios cheerio

      - name: Rulează scraperul
        run: node dorin_buraca_loto-system.js

      - name: Mutare fișier generat în folderul public
        run: |
          mkdir -p public
          mv loto-649.json public/loto-649.json

      - name: Publicare pe GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
